# GitHub Actions Auto-Deploy Setup
name: Auto-Deploy Web App Updates

on:
  push:
    branches: [ main ]
    paths:
      - 'book2/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js (if needed)
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        
    - name: Notify deployment success
      run: echo "🚀 Deployment completed successfully!"